# Lab | Data Aggregation and Filtering

Objective: Use Python programming techniques to filter and order data subsets, group data by one or more variables, and use aggregation functions to obtain insights, and derive meaningful conclusions from the data.

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing first data cleaning, formatting, and structuring.

Start by reading the dataset, standardizing column names, dealing with null values and creating the month column. You can do so by using the functions you developed in previous labs, or by reading the clean dataset you saved in the last lab `data structuring and combining`.

Then, answer the following questions:

1. Create a new DataFrame that only includes customers who have a total_claim_amount greater than $1,000 and have a response of "Yes" to the last marketing campaign.

2. Analyze the average total_claim_amount by each policy type and gender for customers who have responded "Yes" to the last marketing campaign.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the median customer lifetime value by education level and gender.

5. Find the maximum, minimum, and average number of open complaints by state and policy type.

6. The marketing team wants to analyze the number of policies sold by state and month.

Present the data in a table where the months are arranged as columns and the states are arranged as rows.

7. Display a new DataFrame that contains the number of policies sold by month by state for the top 3 states with the highest number of policies sold.

*Hint:* 
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

8. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [1]:
import pandas as pd
import numpy as np

In [16]:
marketing_customer_analysis_cleaned = pd.read_csv("marketing_customer_analysis_cleaned.csv")

marketing_customer_analysis_cleaned

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,Employment Status,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
1,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
2,10,HG93801,Arizona,5154.764074,No,Extended,High School or Below,1/2/11,Employed,M,...,0.0,1,Corporate Auto,Corporate L3,Offer2,Branch,442.521087,SUV,Large,A
3,13,KR82385,California,5454.587929,No,Basic,Master,1/26/11,Employed,M,...,0.0,4,Personal Auto,Personal L3,Offer4,Call Center,331.200000,Two-Door Car,Medsize,A
4,16,FH51383,California,5326.677654,No,Basic,High School or Below,2/7/11,Employed,F,...,0.0,6,Personal Auto,Personal L3,Offer4,Call Center,300.528579,Two-Door Car,Large,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4538,10902,PP30874,California,3579.023825,No,Extended,High School or Below,1/24/11,Employed,F,...,2.0,1,Personal Auto,Personal L2,Offer2,Agent,655.200000,Four-Door Car,Medsize,A
4539,10903,SU71163,Arizona,2771.663013,No,Basic,College,1/7/11,Employed,M,...,4.0,1,Personal Auto,Personal L2,Offer2,Branch,355.200000,Two-Door Car,Medsize,A
4540,10904,QI63521,Nevada,19228.463620,No,Basic,High School or Below,2/24/11,Unemployed,M,...,0.0,2,Personal Auto,Personal L2,Offer1,Branch,897.600000,Luxury SUV,Medsize,A
4541,10906,KX53892,Oregon,5259.444853,No,Basic,College,1/6/11,Employed,F,...,0.0,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
4542,10908,WA60547,California,11971.977650,No,Premium,College,2/13/11,Employed,F,...,4.0,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A

In [38]:
print(marketing_customer_analysis_cleaned['State'].unique())

['Washington' 'Oregon' 'Arizona' 'California' 'Nevada']

In [ ]:
# 1

In [18]:
high_total_claim_amount_df = marketing_customer_analysis_cleaned[(marketing_customer_analysis_cleaned['Total Claim Amount'] > 1000) & (marketing_customer_analysis_cleaned['Response'] == 'Yes')].copy()

In [19]:
high_total_claim_amount_df

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,Employment Status,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
103,236,YJ16163,Oregon,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,...,0.0,1,Special Auto,Special L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
167,419,GW43195,Oregon,25807.063000,Yes,Extended,College,2/13/11,Employed,F,...,1.0,2,Personal Auto,Personal L2,Offer1,Branch,1027.200000,Luxury Car,Small,A
171,442,IP94270,Arizona,13736.132500,Yes,Premium,Master,2/13/11,Disabled,F,...,0.0,8,Personal Auto,Personal L2,Offer1,Web,1261.319869,SUV,Medsize,A
231,587,FJ28407,California,5619.689084,Yes,Premium,High School or Below,1/26/11,Unemployed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Web,1027.000029,SUV,Medsize,A
616,1527,TU53781,Oregon,8427.172486,Yes,Extended,Bachelor,2/10/11,Employed,F,...,1.0,1,Corporate Auto,Corporate L3,Offer1,Agent,1032.000000,Luxury SUV,Medsize,A
717,1809,QO62792,Oregon,7840.165778,Yes,Extended,College,1/14/11,Employed,M,...,2.0,1,Personal Auto,Personal L3,Offer2,Agent,1008.000000,Luxury SUV,Small,A
805,2027,TA66375,Oregon,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,...,0.0,1,Corporate Auto,Corporate L2,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
850,2125,JC11405,Oregon,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,...,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
1130,2865,FH77504,California,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
1613,3958,KC26486,Arizona,8427.172486,Yes,Extended,Bachelor,2/10/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer1,Agent,1032.000000,Luxury SUV,Medsize,A
1840,4475,WP58340,Arizona,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,...,0.0,1,Personal Auto,Personal L2,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
1861,4521,LT72149,Nevada,5619.689084,Yes,Premium,High School or Below,1/26/11,Unemployed,M,...,0.0,1,Personal Auto,Personal L2,Offer2,Web,1027.000029,SUV,Medsize,A
1876,4566,TC99043,California,13736.132500,Yes,Premium,Master,2/13/11,Disabled,F,...,0.0,8,Personal Auto,Personal L2,Offer1,Web,1261.319869,SUV,Medsize,A
2052,5013,GP83239,California,7840.165778,Yes,Extended,College,1/14/11,Employed,M,...,2.0,1,Personal Auto,Personal L3,Offer2,Agent,1008.000000,Luxury SUV,Small,A
2184,5331,UT48216,Nevada,7840.165778,Yes,Extended,College,1/14/11,Employed,M,...,2.0,1,Personal Auto,Personal L1,Offer2,Agent,1008.000000,Luxury SUV,Small,A
2242,5489,TQ84956,California,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,...,0.0,1,Corporate Auto,Corporate L3,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
2411,5896,TY31217,Washington,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
2947,7255,PN98247,California,7840.165778,Yes,Extended,College,1/14/11,Employed,M,...,2.0,1,Personal Auto,Personal L3,Offer2,Agent,1008.000000,Luxury SUV,Small,A
3425,8340,MJ51323,Oregon,8427.172486,Yes,Extended,Bachelor,2/10/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer1,Agent,1032.000000,Luxury SUV,Medsize,A
3436,8367,AJ89108,California,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
3488,8505,DT77901,Oregon,10179.717040,Yes,Premium,Bachelor,1/5/11,Retired,F,...,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1300.800000,Luxury SUV,Medsize,A
3566,8662,YU86361,Washington,19160.989940,Yes,Extended,Master,2/20/11,Employed,F,...,0.0,7,Personal Auto,Personal L1,Offer2,Agent,1294.700423,Luxury SUV,Medsize,A
3635,8835,XT93203,California,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,...,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
3955,9498,IV54766,Oregon,19160.989940,Yes,Extended,Master,2/20/11,Employed,F,...,0.0,7,Personal Auto,Personal L1,Offer2,Agent,1294.700423,Luxury SUV,Medsize,A
3985,9581,GD55093,California,19160.989940,Yes,Extended,Master,2/20/11,Employed,F,...,0.0,7,Personal Auto,Personal L1,Offer2,Agent,1294.700423,Luxury SUV,Medsize,A
4164,10009,YP53257,Oregon,10179.717040,Yes,Premium,Bachelor,1/5/11,Retired,F,...,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1300.800000,Luxury SUV,Medsize,A
4459,10708,CK39096,Oregon,5619.689084,Yes,Premium,High School or Below,1/26/11,Unemployed,M,...,0.0,1,Personal Auto,Personal L3,Offer2,Web,1027.000029,SUV,Medsize,A

In [ ]:
# 2

In [20]:
high_total_claim_amount_df = marketing_customer_analysis_cleaned[marketing_customer_analysis_cleaned['Response'] =='Yes'].copy()

claim_amount_avg = high_total_claim_amount_df.groupby(['Policy Type', 'Gender'])['Total Claim Amount'].mean()

print(claim_amount_avg)

Policy Type     Gender
Corporate Auto  F         404.104008
                M         391.370774
Personal Auto   F         457.056315
                M         472.489180
Special Auto    F         495.689401
                M         368.523035
Name: Total Claim Amount, dtype: float64

In [ ]:
# 3

In [21]:
customers_by_state = marketing_customer_analysis_cleaned['State'].value_counts()

filtered_customers_by_state = customers_by_state[customers_by_state > 500]

print(filtered_customers_by_state)

California    1552
Oregon        1281
Arizona        868
Name: State, dtype: int64

In [ ]:
# 4

In [22]:
clv_median = marketing_customer_analysis_cleaned.groupby(['Education', 'Gender'])['Customer Lifetime Value'].median()

print(clv_median)

Education             Gender
Bachelor              F         5752.485185
                      M         5797.377350
College               F         5642.596077
                      M         6005.847375
Doctor                F         5789.850900
                      M         5843.989737
High School or Below  F         5978.754765
                      M         6081.481291
Master                F         5714.165863
                      M         5512.342258
Name: Customer Lifetime Value, dtype: float64

In [ ]:
# 5

In [24]:
max_open_complaints = marketing_customer_analysis_cleaned.groupby(['State', 'Policy Type'])['Number of Open Complaints'].max()

min_open_complaints = marketing_customer_analysis_cleaned.groupby(['State', 'Policy Type'])['Number of Open Complaints'].min()

avg_open_complaints = marketing_customer_analysis_cleaned.groupby(['State', 'Policy Type'])['Number of Open Complaints'].mean()

print("Maximum number of open complaints:")
print(max_open_complaints)
print("\nMinimum number of open complaints:")
print(min_open_complaints)
print("\nAverage number of open complaints:")
print(avg_open_complaints)

Maximum number of open complaints:
State       Policy Type
Arizona     Corporate Auto    5.0
            Personal Auto     5.0
            Special Auto      3.0
California  Corporate Auto    4.0
            Personal Auto     5.0
            Special Auto      4.0
Nevada      Corporate Auto    3.0
            Personal Auto     5.0
            Special Auto      3.0
Oregon      Corporate Auto    4.0
            Personal Auto     5.0
            Special Auto      5.0
Washington  Corporate Auto    4.0
            Personal Auto     5.0
            Special Auto      4.0
Name: Number of Open Complaints, dtype: float64

Minimum number of open complaints:
State       Policy Type
Arizona     Corporate Auto    0.0
            Personal Auto     0.0
            Special Auto      0.0
California  Corporate Auto    0.0
            Personal Auto     0.0
            Special Auto      0.0
Nevada      Corporate Auto    0.0
            Personal Auto     0.0
            Special Auto      0.0
Oregon      Corporate Auto    0.0
            Personal Auto     0.0
            Special Auto      0.0
Washington  Corporate Auto    0.0
            Personal Auto     0.0
            Special Auto      0.0
Name: Number of Open Complaints, dtype: float64

Average number of open complaints:
State       Policy Type
Arizona     Corporate Auto    0.456790
            Personal Auto     0.413374
            Special Auto      0.229167
California  Corporate Auto    0.296703
            Personal Auto     0.398589
            Special Auto      0.388889
Nevada      Corporate Auto    0.393617
            Personal Auto     0.422492
            Special Auto      0.285714
Oregon      Corporate Auto    0.331984
            Personal Auto     0.373444
            Special Auto      0.328571
Washington  Corporate Auto    0.467532
            Personal Auto     0.409836
            Special Auto      0.562500
Name: Number of Open Complaints, dtype: float64

In [ ]:
# 6

In [33]:
marketing_customer_analysis_cleaned["Effective To Date"] = pd.to_datetime(marketing_customer_analysis_cleaned["Effective To Date"])

marketing_customer_analysis_cleaned["Month"] = marketing_customer_analysis_cleaned["Effective To Date"].dt.strftime("%b")

policies_sold_pivot = pd.pivot_table(marketing_customer_analysis_cleaned, values='Number of Policies', index='State', columns='Month', aggfunc='sum')

print(policies_sold_pivot)

Month        Feb   Jan
State
Arizona     1297  1344
California  2158  2439
Nevada       567   666
Oregon      1885  2009
Washington   589   585

In [ ]:
# 7

In [34]:
policies_sold_by_state_month = marketing_customer_analysis_cleaned.groupby(['State', 'Month']).size().reset_index(name='Count')

sorted_policies_sold = policies_sold_by_state_month.sort_values(by='Count', ascending=False)

top_3_states = sorted_policies_sold['State'].head(3)

new_dataframe = sorted_policies_sold[sorted_policies_sold['State'].isin(top_3_states)]

print(new_dataframe)

        State Month  Count
3  California   Jan    826
2  California   Feb    726
7      Oregon   Jan    676
6      Oregon   Feb    605

In [ ]:
# 8

In [40]:
unpivoted_data = pd.melt(marketing_customer_analysis_cleaned, id_vars='Sales Channel', value_vars='Response', value_name='Response').dropna()
filtered_data = unpivoted_data[unpivoted_data['Response'] == 'Yes']

response_rate = filtered_data.groupby('Sales Channel').size() / unpivoted_data.groupby('Sales Channel').size()

print(response_rate)

Sales Channel
Agent          0.189606
Branch         0.098716
Call Center    0.109853
Web            0.134238
dtype: float64

/var/folders/d9/783c_j055nj0b0y037qm_1zc0000gn/T/ipykernel_38088/1993345617.py:1: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  unpivoted_data = pd.melt(marketing_customer_analysis_cleaned, id_vars='Sales Channel', value_vars='Response', value_name='Response').dropna()